# Project-wide Gradle settings.
# For more details on how to configure your build, see
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Dfile.encoding=UTF-8

# AndroidX is the successor to the Android Support Library.
android.useAndroidX=true

# Enable non-transitive R classes for faster builds.
android.nonTransitiveRClass=true

# Enable Kotlin configuration cache and parallel builds.
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Kotlin styling
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
