package com.smartplanner.model

import java.util.UUID

/**
 * Type of action recommended by the AI Coach.
 */
enum class ChangeType(val label: String) {
    SHRINK_TO_MIN("Shrink to Minimum Version"),
    CHANGE_ANCHOR("Change Anchor Trigger"),
    PAUSE_HABIT("Pause Habit"),
    GROW_TARGET("Level Up Target")
}

/**
 * Status of a human-in-the-loop proposal.
 */
enum class ProposalStatus {
    PENDING,
    ACCEPTED,
    REJECTED
}

/**
 * A concrete adjustment proposed by the Weekly Coach Agent.
 * Preserves human-in-the-loop guarantee (cannot be applied without user approval).
 */
data class ProposedChange(
    val id: String = UUID.randomUUID().toString(),
    val habitId: String,
    val habitTitle: String,
    val changeType: ChangeType,
    val oldValue: String,
    val newValue: String,
    val reason: String,
    val expectedImpact: String,
    val status: ProposalStatus = ProposalStatus.PENDING
)

/**
 * Single step in the Agent's reasoning trace for transparency.
 */
data class AgentStepLog(
    val stepNumber: Int,
    val toolName: String,
    val inputSummary: String,
    val outputSummary: String,
    val rationale: String
)

/**
 * Complete Weekly Review generated by the Agent or Offline Fallback.
 */
data class WeeklyReview(
    val id: String = UUID.randomUUID().toString(),
    val startDate: String,
    val endDate: String,
    val summaryPraise: String,
    val gentleAdvice: String,
    val proposedChanges: List<ProposedChange> = emptyList(),
    val agentTrace: List<AgentStepLog> = emptyList(),
    val completedCount: Int = 0,
    val partialCount: Int = 0,
    val skippedCount: Int = 0,
    val isReviewed: Boolean = false
)
